### ISSUE TITLE
Old school usage example is borked

### ISSUE THREAD

**Issue by Joshua2504** [bopen/leaflet-area-selection#21]
Hey,

the Old School Usage example linked in the README seems to use an old Version and is not working.

Could you update it?

**Comment by keul** [comment]
Done (but this is still tested with old version leaflet… there are never fixed issues with most recent ones)

**Comment by Joshua2504** [comment]
Hey, thank you for the quick reply :)

I just copied the code, but still the coordinates of the selected area are not being shown below the map.

**Comment by keul** [comment]
@Joshua2504 OK now I got it. The old school example is not complete as the live example you can find at https://bopen.github.io/leaflet-area-selection/
It just show how you can integrate the plugin in the leaflet hello world example.

I can improve, but is just a matter of configuring it adding what you can find from this line on: https://github.com/bopen/leaflet-area-selection/blob/dabc22fd8c57b9eebf27bbc642ea3cff51128e58/example/src/index.js#L43
