### ISSUE TITLE
GhostMarkers temporary polygon wrong position

### ISSUE THREAD

**Issue by GruianDavid** [bopen/leaflet-area-selection#4]
Description:
After the polygon is created, any change in zoom level or map drag will result in the wrong position of GhostMarkers temporary polygon while dragging.
![image](https://user-images.githubusercontent.com/17519124/154668138-a07f2586-e185-43c6-b051-552553974980.png)

Steps to reproduce:
Step1: Create a polygon (any kind)
Step2: Drag the map in any direction or zoom in or out
Step3: Create a new Marker from a GhostMarker. (The new area will have a weird position as initial markers changed position in viewport)

Solution:
Within function onGhostMarkerDrag(index) 

the following line:
_this6.ghostPolygon = new leaflet.Polygon([map.containerPointToLatLng(firstPoint.point), latlng, map.containerPointToLatLng(lastPoint.point)], {

Should be changed to:
_this6.ghostPolygon = new leaflet.Polygon([firstPoint.marker._latlng, latlng, lastPoint.marker._latlng], {
or some method more safe than direct referencing of an attribute of the marker.
With this change, the position will be based on actual latlong position and not a fixed area on screen

**Comment by keul** [comment]
Thanks @GruianDavid, no bloody idea how I didn't noticed this before 🙇 

Released 0.6.2
